// Auto-generated from Homeroom exports (Mann Elementary). Historical, read-only.
// Includes a year-round Music season and aggregate parent feedback (no personal info).
export const HISTORICAL_RAW = [
  {
    "name": "Fall 2025",
    "classes": [
      {
        "name": "Crafts & Games",
        "type": "Art",
        "band": "K-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Jaime",
        "provider": "Horace Mann PTSA",
        "enrolled": 24,
        "capacity": 23,
        "outcome": "Completed",
        "feedback": "★ 4.5 · 2 responses · 0% would repeat"
      },
      {
        "name": "Indoor Soccer",
        "type": "Movement",
        "band": "K-3",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Jovone Robinson",
        "provider": "B&B Solutions",
        "enrolled": 19,
        "capacity": 20,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 1 response · 100% would repeat"
      },
      {
        "name": "Floor Hockey",
        "type": "Movement",
        "band": "3-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Mia Douglas",
        "provider": "B&B Solutions",
        "enrolled": 12,
        "capacity": 20,
        "outcome": "Completed",
        "feedback": "★ 3.2 · 4 responses · 25% would repeat"
      },
      {
        "name": "Game Development from Start to Finish",
        "type": "STEM",
        "band": "3-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Art Room",
        "instructor": "Nicholas Brennan",
        "provider": "Open World",
        "enrolled": 10,
        "capacity": 15,
        "outcome": "Completed",
        "feedback": "★ 4.3 · 3 responses · 33% would repeat"
      },
      {
        "name": "Rainy Day Dinner Club",
        "type": "Art",
        "band": "2-5",
        "day": "Wed",
        "start": "14:35",
        "end": "16:05",
        "room": "Art Room",
        "instructor": "",
        "provider": "Rainy Day Dinner Club",
        "enrolled": 14,
        "capacity": 16,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 3 responses · 67% would repeat"
      },
      {
        "name": "Game Design for Young Programmers",
        "type": "STEM",
        "band": "1-3",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "118",
        "instructor": "Russell Higgins",
        "provider": "Open World",
        "enrolled": 13,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Draw. Dream. Design. – An Anime Art Journey",
        "type": "Art",
        "band": "K-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Art Room",
        "instructor": "",
        "provider": "Creatstudioz",
        "enrolled": 15,
        "capacity": 21,
        "outcome": "Completed",
        "feedback": "★ 4.0 · 2 responses · 50% would repeat"
      },
      {
        "name": "Chess Club",
        "type": "STEM",
        "band": "3-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Art Room",
        "instructor": "Ryan Ackerman",
        "provider": "Orlov Chess Academy",
        "enrolled": 16,
        "capacity": 16,
        "outcome": "Completed",
        "feedback": "★ 4.2 · 5 responses · 80% would repeat"
      },
      {
        "name": "Chess Club",
        "type": "STEM",
        "band": "K-2",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "118",
        "instructor": "Ryan Ackerman",
        "provider": "Orlov Chess Academy",
        "enrolled": 17,
        "capacity": 16,
        "outcome": "Completed",
        "feedback": "★ 2.0 · 1 response · 0% would repeat"
      },
      {
        "name": "Volcano Island",
        "type": "STEM",
        "band": "K-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Room 118",
        "instructor": "Mansi Mehta",
        "provider": "Challenge Island of Greater Seattle",
        "enrolled": 18,
        "capacity": 16,
        "outcome": "Completed",
        "feedback": "★ 4.0 · 5 responses · 40% would repeat"
      },
      {
        "name": "Hip Hop Dance",
        "type": "Movement",
        "band": "K-5",
        "day": "Wed",
        "start": "14:35",
        "end": "15:35",
        "room": "Gym",
        "instructor": "Natalie Dukane",
        "provider": "Dukane Studios",
        "enrolled": 30,
        "capacity": 30,
        "outcome": "Completed",
        "feedback": "★ 4.0 · 1 response · 0% would repeat"
      },
      {
        "name": "Spanish Immersion Class",
        "type": "Academic",
        "band": "",
        "day": "Thu",
        "start": "08:10",
        "end": "09:01",
        "room": "Art Room",
        "instructor": "",
        "provider": "Paris Academy Northwest",
        "enrolled": 0,
        "capacity": 18,
        "outcome": "Cancelled"
      },
      {
        "name": "Let Grow Free Play Club",
        "type": "Movement",
        "band": "K-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Horace Mann Playground",
        "instructor": "Amy Compton",
        "provider": "",
        "enrolled": 20,
        "capacity": 40,
        "outcome": "Completed"
      }
    ]
  },
  {
    "name": "Winter 2026",
    "classes": [
      {
        "name": "Bizzy Brains - Entrepreneurship Program for Grades 3 - 5",
        "type": "Academic",
        "band": "2-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:35",
        "room": "Room 118",
        "instructor": "Zainab Kapadia",
        "provider": "Entrepology",
        "enrolled": 14,
        "capacity": 25,
        "outcome": "Completed"
      },
      {
        "name": "Sing and Play: Space Explorers",
        "type": "Art",
        "band": "1-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:20",
        "room": "3rd Grad Pod & Gym for Performance",
        "instructor": "Paige Krumperman",
        "provider": "Sing and Play Productions",
        "enrolled": 19,
        "capacity": 22,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 2 responses · 100% would repeat"
      },
      {
        "name": "Create. Explore. Inspire. – Artists of the Northwest",
        "type": "Art",
        "band": "K-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Art Room",
        "instructor": "Fatima Saeed",
        "provider": "Creatstudioz",
        "enrolled": 20,
        "capacity": 21,
        "outcome": "Completed"
      },
      {
        "name": "Presentation Club",
        "type": "Academic",
        "band": "2-3",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "3rd Grad Pod (upstairs)",
        "instructor": "Prithish Paul",
        "provider": "Horace Mann PTSA",
        "enrolled": 10,
        "capacity": 10,
        "outcome": "Completed"
      },
      {
        "name": "Hip Hop Dance & Fitness",
        "type": "Movement",
        "band": "K-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Natalie Dukane",
        "provider": "Dukane Studios",
        "enrolled": 24,
        "capacity": 30,
        "outcome": "Completed"
      },
      {
        "name": "Spanish Immersion Class",
        "type": "Academic",
        "band": "K-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "3rd Grade POD (upstairs)",
        "instructor": "DIYA JAYACHANDRAN",
        "provider": "Paris Academy Northwest",
        "enrolled": 6,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Rainy Day Dinner Club",
        "type": "Art",
        "band": "2-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:35",
        "room": "Art Room",
        "instructor": "Samantha Smith",
        "provider": "Rainy Day Dinner Club",
        "enrolled": 0,
        "capacity": 16,
        "outcome": "Cancelled"
      },
      {
        "name": "Multi-Sport",
        "type": "Movement",
        "band": "K-2",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Alfredo Castronuevo",
        "provider": "B&B Solutions",
        "enrolled": 14,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Racquet Sports - Pickleball & Badminton",
        "type": "Movement",
        "band": "2-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Alfredo Castronuevo",
        "provider": "B&B Solutions",
        "enrolled": 20,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Awesomesauce Island",
        "type": "STEM",
        "band": "1-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "Karen Russell",
        "provider": "Challenge Island of Greater Seattle",
        "enrolled": 0,
        "capacity": 16,
        "outcome": "Cancelled"
      },
      {
        "name": "3rd-5th Basketball Class!",
        "type": "Movement",
        "band": "3-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Ben Cando",
        "provider": "Backboard Basics",
        "enrolled": 11,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Chess Club",
        "type": "STEM",
        "band": "K-2",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Room 118",
        "instructor": "Tim Moroney",
        "provider": "Excel With Chess",
        "enrolled": 15,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Game Design for Young Programmers",
        "type": "STEM",
        "band": "K-2",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Room 118",
        "instructor": "Roberto Velasquez Suchini",
        "provider": "Open World",
        "enrolled": 6,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Game Development from Start to Finish",
        "type": "STEM",
        "band": "3-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "Room 118",
        "instructor": "Dillon van Rensburg",
        "provider": "Open World",
        "enrolled": 9,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Chess Club",
        "type": "STEM",
        "band": "3-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "Tim Moroney",
        "provider": "Excel With Chess",
        "enrolled": 13,
        "capacity": 26,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 1 response · 100% would repeat"
      },
      {
        "name": "Math Club (4-5)",
        "type": "Academic",
        "band": "4-5",
        "day": "Tue",
        "start": "16:05",
        "end": "16:55",
        "room": "4th Grade POD (upstairs)",
        "instructor": "Priya Bhale",
        "provider": "Horace Mann PTSA",
        "enrolled": 14,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Math Club (2-3)",
        "type": "Academic",
        "band": "2-3",
        "day": "Mon",
        "start": "16:05",
        "end": "16:55",
        "room": "4th Grade POD (upstairs)",
        "instructor": "Ganga Narayanan",
        "provider": "Horace Mann PTSA",
        "enrolled": 10,
        "capacity": 10,
        "outcome": "Completed"
      },
      {
        "name": "Math Club (K-1)",
        "type": "Academic",
        "band": "K-1",
        "day": "Thu",
        "start": "16:05",
        "end": "16:55",
        "room": "4th Grade POD (upstairs)",
        "instructor": "Matthew Whilden",
        "provider": "Horace Mann PTSA",
        "enrolled": 13,
        "capacity": 12,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 1 response · 100% would repeat"
      },
      {
        "name": "Crafts & Games",
        "type": "Art",
        "band": "K-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "Jaime",
        "provider": "Horace Mann PTSA",
        "enrolled": 21,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Aspiring Authors Creative Writing Workshop",
        "type": "Academic",
        "band": "2-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "",
        "provider": "Redmond Northeast Best Brains",
        "enrolled": 11,
        "capacity": 20,
        "outcome": "Completed"
      }
    ]
  },
  {
    "name": "Spring 2026",
    "classes": [
      {
        "name": "Storytopia Island",
        "type": "STEM",
        "band": "K-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "Karen Russell",
        "provider": "Challenge Island of Greater Seattle",
        "enrolled": 11,
        "capacity": 16,
        "outcome": "Completed"
      },
      {
        "name": "Rainy Day Dinner Club",
        "type": "Art",
        "band": "1-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:35",
        "room": "Art and Science Room",
        "instructor": "Samantha Smith",
        "provider": "Rainy Day Dinner Club",
        "enrolled": 8,
        "capacity": 16,
        "outcome": "Completed"
      },
      {
        "name": "Chess Club",
        "type": "STEM",
        "band": "K-2",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "118",
        "instructor": "Tim Moroney",
        "provider": "Excel With Chess",
        "enrolled": 17,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Chess Club",
        "type": "STEM",
        "band": "3-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "2nd Grade Pod (1st Floor)",
        "instructor": "Tim Moroney",
        "provider": "Excel With Chess",
        "enrolled": 15,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Create • Explore • Inspire: Color Theory",
        "type": "Art",
        "band": "K-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "Fatima Saeed",
        "provider": "Creatstudioz",
        "enrolled": 14,
        "capacity": 21,
        "outcome": "Completed"
      },
      {
        "name": "Tweetering Architecture: A Garden for Birds",
        "type": "STEM",
        "band": "2-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:20",
        "room": "118",
        "instructor": "Shima Baradaran Mohajeri",
        "provider": "PlayArchy Lab",
        "enrolled": 7,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Emerald City Ball Hockey",
        "type": "Movement",
        "band": "2-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Salvatore Ippolito",
        "provider": "Emerald City Ball Hockey",
        "enrolled": 0,
        "capacity": 22,
        "outcome": "Cancelled"
      },
      {
        "name": "Hip Hop Dance",
        "type": "Movement",
        "band": "K-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Natalie Dukane",
        "provider": "Dukane Studios",
        "enrolled": 12,
        "capacity": 30,
        "outcome": "Completed"
      },
      {
        "name": "Game Design for Young Programmers",
        "type": "STEM",
        "band": "K-2",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "118",
        "instructor": "Roberto Velasquez Suchini",
        "provider": "Open World",
        "enrolled": 4,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Game Development from Start to Finish",
        "type": "STEM",
        "band": "3-5",
        "day": "Fri",
        "start": "16:05",
        "end": "17:05",
        "room": "Art and Science Room",
        "instructor": "Bruce McCubbin",
        "provider": "Open World",
        "enrolled": 14,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Indian Classical Dance - Odissi (Tiny Dancers, Big Legends)",
        "type": "Movement",
        "band": "K-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Sharbani Datta",
        "provider": "Horace Mann PTSA",
        "enrolled": 10,
        "capacity": 15,
        "outcome": "Completed"
      },
      {
        "name": "Math Club (K-1)",
        "type": "Academic",
        "band": "K-1",
        "day": "Tue",
        "start": "16:05",
        "end": "16:55",
        "room": "2nd Grade Pod (downstairs)",
        "instructor": "Matthew Whilden",
        "provider": "Horace Mann PTSA",
        "enrolled": 10,
        "capacity": 12,
        "outcome": "Completed"
      },
      {
        "name": "Crafts & Games",
        "type": "Art",
        "band": "K-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "2nd Grade Pod",
        "instructor": "Jaime",
        "provider": "Horace Mann PTSA",
        "enrolled": 22,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Pickleball",
        "type": "Movement",
        "band": "K-2",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Gym",
        "instructor": "Brandon Larrieu",
        "provider": "B&B Solutions",
        "enrolled": 10,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Flag Football and Basketball",
        "type": "Movement",
        "band": "2-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Field and Outdoor Courts",
        "instructor": "Brandon Larrieu",
        "provider": "B&B Solutions",
        "enrolled": 12,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Sing and Play: Fairy Tale Mystery",
        "type": "Art",
        "band": "K-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "1st Grade Pod & Gym",
        "instructor": "Paige Krumperman",
        "provider": "Sing and Play Productions",
        "enrolled": 9,
        "capacity": 20,
        "outcome": "Completed"
      },
      {
        "name": "Super Speakers Public Speaking Workshop",
        "type": "Academic",
        "band": "2-4",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "118",
        "instructor": "",
        "provider": "Redmond Northeast Best Brains",
        "enrolled": 8,
        "capacity": 10,
        "outcome": "Completed"
      },
      {
        "name": "WonderLab STEAM Monthly Workshop",
        "type": "STEM",
        "band": "3-5",
        "day": "Fri",
        "start": "17:30",
        "end": "18:30",
        "room": "118",
        "instructor": "Apurva Singh",
        "provider": "Horace Mann PTSA",
        "enrolled": 9,
        "capacity": 20,
        "outcome": "Completed"
      }
    ]
  },
  {
    "name": "Music (2025–26)",
    "yearLong": true,
    "classes": [
      {
        "name": "Choir",
        "type": "Art",
        "band": "3-5",
        "day": "Wed",
        "start": "08:15",
        "end": "09:10",
        "room": "Music Room",
        "instructor": "Brad McRae",
        "provider": "",
        "enrolled": 67,
        "capacity": 55,
        "outcome": "Completed",
        "feedback": "★ 4.8 · 6 responses · 100% would repeat"
      },
      {
        "name": "Beginner Orchestra",
        "type": "Art",
        "band": "2-5",
        "day": "Mon",
        "start": "16:05",
        "end": "17:05",
        "room": "Music Room",
        "instructor": "Courtney Yeates",
        "provider": "Fifth Symphony Music",
        "enrolled": 21,
        "capacity": 50,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 4 responses · 100% would repeat"
      },
      {
        "name": "Intermediate Orchestra",
        "type": "Art",
        "band": "2-5",
        "day": "Wed",
        "start": "14:35",
        "end": "15:35",
        "room": "Room 118",
        "instructor": "Courtney Yeates",
        "provider": "Fifth Symphony Music",
        "enrolled": 10,
        "capacity": 30,
        "outcome": "Completed",
        "feedback": "★ 5.0 · 4 responses · 100% would repeat"
      },
      {
        "name": "Band",
        "type": "Art",
        "band": "3-5",
        "day": "Tue",
        "start": "16:05",
        "end": "17:05",
        "room": "Music Room",
        "instructor": "Shannon Nelson",
        "provider": "",
        "enrolled": 11,
        "capacity": 15,
        "outcome": "Completed",
        "feedback": "★ 4.2 · 5 responses · 60% would repeat"
      },
      {
        "name": "Band",
        "type": "Art",
        "band": "3-5",
        "day": "Thu",
        "start": "16:05",
        "end": "17:05",
        "room": "Music Room",
        "instructor": "Shannon Nelson",
        "provider": "",
        "enrolled": 10,
        "capacity": 15,
        "outcome": "Completed",
        "feedback": "★ 4.2 · 5 responses · 60% would repeat"
      }
    ]
  }
];
